STANDART_RPM = 1480
ANOMALY_COEFFICIENT = 1.5

REAR_BEARING_AVG_TEMPERATURE = 49.68
FRONT_BEARING_AVG_TEMPERATURE = 49.60

FRONT_BEARING_VERTICAL_VIBRATION_COEFFICIENT = 0.7
REAR_BEARING_VERTICAL_VIBRATION_COEFFICIENT = 0.3